service:
  name: kyiv-affiche

org: w260698 
app: my-first-app

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Resource: "arn:aws:lambda:us-east-1:*:*"
      Action:
        - lambda:*

functions:
  bot:
    handler: handlerBot.handler
    timeout: 10
    environment:
      NODE_ENV: ${self:provider.stage}
      BOT_TOKEN: ${file(config.${self:provider.stage}.json):BOT_TOKEN}
      ADMIN_TOKEN: ${file(config.${self:provider.stage}.json):ADMIN_TOKEN}
      CACHE_ENABLED: ${file(config.${self:provider.stage}.json):CACHE_ENABLED}
      REDIS_URL: ${file(config.${self:provider.stage}.json):REDIS_URL}
    events:
      - http:
          method: post
          path: bot/handler
          cors: true
      - https:
          method: post
          path: bot/handler
          cors: true
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            action: checkForNew
